export const FETCH_GET_BOARDLIST = 'board/FETCH_GET_BOARDLIST';
// export const FETCH_GET_BOARDLOADING = 'board/FETCH_GET_BOARDLOADING';
export const FETCH_GET_BOARDLIST_SUCCESS = 'board/FETCH_GET_BOARDLIST_SUCCESS';

export const FETCH_GET_BOARDVIEW = 'board/FETCH_GET_BOARDVIEW';



export const FETCH_GET_BOARDCREATE = 'board/FETCH_GET_BOARDCREATE';
export const FETCH_GET_BOARDVIEW_SUCCESS = 'board/FETCH_GET_BOARDVIEW_SUCCESS';

